apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-pvc
spec:
  storageClassName: iomesh-csi-driver-default
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: fio
  labels:
    app: fio
spec:
  volumes:
    - name: fio-pvc
      persistentVolumeClaim:
        claimName: fio-pvc
  containers:
    - name: fio
      image: clusterhq/fio-tool
      command:
        - tail
      args:
        - '-f'
        - /dev/null
      imagePullPolicy: IfNotPresent
      volumeDevices:
        - devicePath: /mnt/fio
          name: fio-pvc
  restartPolicy: Always
