apiVersion: v1
kind: ServiceAccount
metadata:
  name: zbs-csi-controller-account
  namespace: iomesh-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zbs-csi-provisioner-binding
subjects:
  - kind: ServiceAccount
    name: zbs-csi-controller-account
    namespace: iomesh-system
roleRef:
  kind: ClusterRole
  name: zbs-csi-provisioner-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zbs-csi-attacher-binding
subjects:
  - kind: ServiceAccount
    name: zbs-csi-controller-account
    namespace: iomesh-system
roleRef:
  kind: ClusterRole
  name: zbs-csi-attacher-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zbs-csi-snapshotter-binding
subjects:
  - kind: ServiceAccount
    name: zbs-csi-controller-account
    namespace: iomesh-system
roleRef:
  kind: ClusterRole
  name: zbs-csi-snapshotter-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zbs-csi-resizer-binding
subjects:
  - kind: ServiceAccount
    name: zbs-csi-controller-account
    namespace: iomesh-system
roleRef:
  kind: ClusterRole
  name: zbs-csi-resizer-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zbs-csi-driver-controller-binding
subjects:
  - kind: ServiceAccount
    name: zbs-csi-controller-account
    namespace: iomesh-system
roleRef:
  kind: ClusterRole
  name: zbs-csi-driver-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zbs-csi-node-account
  namespace: iomesh-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zbs-csi-driver-node-binding
subjects:
  - kind: ServiceAccount
    name: zbs-csi-node-account
    namespace: iomesh-system
roleRef:
  kind: ClusterRole
  name: zbs-csi-driver-role
  apiGroup: rbac.authorization.k8s.io
