name: documentation

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  checks:
    # pull request
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          run: |
            npm ci
            npm run build

  gh-release:
    # pull request merged
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Build static site
        run: |
          npm install
          npm run build

      - name: Release to github pages
        uses: crazy-max/ghaction-github-pages@v2.0.0
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
